version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: routemaster

  routemaster:
    build: .
    image: routemaster
    command:
      - routemaster
      - --config-file=config.dev.yaml
      - serve
      - --debug
    volumes:
      - .:/routemaster/app
    ports:
      - "2017:2017"
    working_dir: /routemaster/app
    environment:
      DB_NAME: routemaster
      DB_USER: routemaster
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
