version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: routemaster

  serve:
    build: .
    image: routemaster:dev
    entrypoint:
      - routemaster
      - --config-file=config.dev.yaml
      - serve
      - --debug
    volumes:
      - .:/routemaster/app
    ports:
      - "2017:2017"
    working_dir: /routemaster/app
    environment:
      DB_NAME: routemaster
      DB_USER: routemaster
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  migrate:
    build: .
    image: routemaster:migrations
    entrypoint:
      - alembic
      - upgrade
      - head
    volumes:
      - .:/routemaster/app
    working_dir: /routemaster/app
    environment:
      DB_NAME: routemaster
      DB_USER: routemaster
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  validate:
    build: .
    image: routemaster:dev
    entrypoint:
      - routemaster
      - --config-file=config.dev.yaml
      - validate
    volumes:
      - .:/routemaster/app
    working_dir: /routemaster/app
    environment:
      DB_NAME: routemaster
      DB_USER: routemaster
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
