version: 2

jobs:
  build:
    working_directory: ~/routemaster
    docker:
      # First container is where our steps run.
      - image: circleci/python:3.6.3
        environment:
          - PG_HOST=localhost
          - PG_PORT=5432
          - PG_DB=routemaster
          - PG_USER=ubuntu

      # Ancilliary containers
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=routemaster

    steps:
      - checkout

        # Set up a cached virtualenv in which to install tox
      - restore_cache:
          key: deps-venv-{{ .Branch }}-2.9.1
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox==2.9.1
      - save_cache:
          key: deps-venv-{{ .Branch }}-2.9.1
          paths:
            - "venv"

      # Setup the database
      - run:
          name: Install Dockerize Utility
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Database with Dockerize
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Add Postgres binaries to $PATH
          command: echo '/usr/lib/postgresql/9.6/bin/:$PATH' >> $BASH_ENV
      - run:
          name: Setup Database
          command: |
            sudo -u $PG_USER psql -d $PG_DB <<END_SQL
            CREATE TABLE labels (
            	name VARCHAR NOT NULL,
            	state_machine VARCHAR NOT NULL,
            	context JSONB,
            	PRIMARY KEY (name, state_machine)
            );
            CREATE TABLE label_history (
            	id SERIAL NOT NULL,
            	label_name VARCHAR,
            	label_state_machine VARCHAR,
            	created TIMESTAMP WITHOUT TIME ZONE,
            	forced BOOLEAN,
            	old_state VARCHAR,
            	new_state VARCHAR,
            	PRIMARY KEY (id),
            	FOREIGN KEY(label_name, label_state_machine) REFERENCES labels (name, state_machine)
            );
            CREATE TABLE state_machines (
            	name VARCHAR NOT NULL,
            	updated TIMESTAMP WITHOUT TIME ZONE,
            	PRIMARY KEY (name)
            );
            CREATE TABLE states (
            	name VARCHAR NOT NULL,
            	state_machine INTEGER NOT NULL,
            	deprecated BOOLEAN,
            	updated TIMESTAMP WITHOUT TIME ZONE,
            	PRIMARY KEY (name, state_machine),
            	FOREIGN KEY(state_machine) REFERENCES state_machines (name)
            );
            END_SQL

      # Run tox, caching the .tox directory
      - restore_cache:
          key: deps-tox-{{ .Branch }}-{{ checksum "scripts/linting/requirements.txt" }}-{{ checksum "scripts/testing/requirements.txt" }}-{{ checksum "setup.py" }}
      - run:
          command: |
            . venv/bin/activate
            tox
      - save_cache:
          key: deps-tox-{{ .Branch }}-{{ checksum "scripts/linting/requirements.txt" }}-{{ checksum "scripts/testing/requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - ".tox"

      # Testing done, store results
      - store_test_results:
          path: build/results
      - store_artifacts:
          path: build/artifacts/coverage
          destination: coverage
