version: 2

jobs:
  build:
    working_directory: ~/routemaster
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout

      - restore_cache: # Set up a cached virtualenv in which to install tox
          key: deps-venv-{{ .Branch }}-2.9.1
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox==2.9.1
      - save_cache:
          key: key: deps-venv-{{ .Branch }}-2.9.1
          paths:
            - "venv"

      - restore_cache: # Run tox, caching the .tox directory
          key: deps-tox-{{ .Branch }}-{{ checksum "scripts/linting/requirements.txt" }}-{{ checksum "scripts/testing/requirements.txt" }}
      - run:
          command: |
            . venv/bin/activate
            tox
      - save_cache:
          key: deps-tox-{{ .Branch }}-{{ checksum "scripts/linting/requirements.txt" }}-{{ checksum "scripts/testing/requirements.txt" }}
          paths:
            - ".tox"

      - store_test_results: # Testing done, store results
          path: build/pytest
