$schema: http://json-schema.org/draft-06/schema#
title: Configuration
type: object
properties:
  database:
    type: object
    properties:
      host:
        type: string
      port:
        type: number
      name:
        type: string
      username:
        type: string
      password:
        type: string
  state_machines:
    type: object
    additionalProperties:
      title: State Machine
      type: object
      properties:
        states:
          title: States
          type: array
          minItems: 1
          uniqueItems: true
          items:
            title: State
            anyOf:
              - type: object
                properties:
                  gate: &state_name_definition
                    type: string
                    pattern: '^[a-zA-Z0-9_]+$'
                  triggers:
                    title: Triggers
                    type: array
                    uniqueItems: true
                    items:
                      title: Trigger
                      anyOf:
                        - type: object
                          properties:
                            metadata: &dotted_path_definition
                              type: string
                              pattern: '^[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*$'
                          required:
                            - metadata
                          additionalProperties: false
                        - type: object
                          properties:
                            time:
                              type: string
                              pattern: '^[0-9]{1,2}h[0-9]{2}m$'
                        - type: object
                          properties:
                            interval:
                              type: string
                              pattern: '^[0-9]*d?[0-9]*h?[0-9]*m?$'
                  exit_condition:
                    title: Exit condition
                    anyOf:
                      - type: string
                        pattern: '^.+$'
                      - type: boolean
                  next: &next_definition
                    title: Next state
                    anyOf:
                      - type: string
                      - type: object
                        properties:
                          type:
                            const: 'constant'
                          state: *state_name_definition
                        required:
                          - type
                          - state
                        additionalProperties: false
                      - type: object
                        properties:
                          type:
                            const: 'metadata'
                          path: *dotted_path_definition
                          destinations:
                            type: array
                            minItems: 1
                            uniqueItems: true
                            items:
                              title: Context-switched destination
                              type: object
                              properties:
                                state: *state_name_definition
                                value:
                                  title: JSON-compatible atomic value
                              required:
                                - state
                                - value
                              additionalProperties: false
                        required:
                          - type
                          - destinations
                        additionalProperties: false
                required:
                  - gate
                  - exit_condition
                additionalProperties: false
              - type: object
                properties:
                  action: *state_name_definition
                  webhook:
                    type: string
                    pattern: '^https?://.'
                  next: *next_definition
                required:
                  - action
                  - webhook
                  - next
                additionalProperties: false
required:
  - state_machines
additionalProperties: false
